### ISSUE TITLE
Working on OSX?

### ISSUE THREAD

**Issue by marleyjaffe** [laserbat/mandelbrot.sed#3]
I am attempting to run this on OSX but am getting the following error: `-bash: ./mandelbrot.sed: /bin/sed: bad interpreter: No such file or directory`. Any ideas? I'll continue to investigate and post my solution if I find a fix.

**Comment by laserbat** [comment]
This code depends on GNU Sed, which isn't available on OSX by default. Here's a stackoverflow answer explaining how to install and use it: https://stackoverflow.com/a/33756193

You will probably need to replace the first line of mandelbrot.sed, replacing /bin/sed with path to the GNU Sed is installed to.

**Comment by marleyjaffe** [comment]
Thanks for the explanation, After installing GNU-Sed via Brew, I updated the file to have `/usr/local/bin/gsed` which enabled everything else to work as expected. Thanks!
